### ISSUE TITLE
add wordwrap wrapper to do utf8 safe wrapping

### ISSUE THREAD

**Issue by Phorum** [Phorum/Core#863]
currently code uses wordwrap which is not utf8 (or any other multibyte) safe.

attaching patch that adds the wrapper and replaces calls in core code

Reported by: glen
Imported from TRAC: http://trac.phorum.org/ticket/971

**Comment by glensc** [comment]
git url for same patch:

https://github.com/pld-linux/phorum/blob/master/wordwrap.patch

**Comment by oricgn** [comment]
Hi Elan,

instead of putting the new phorum_wordwrap function in common.php it seems better to use /include/format_functions.php.

I wouldn't change /include/cache/file.php since wordwrap is used with an md5 hash.

Regards
Oliver

**Comment by glensc** [comment]
the patch was for 5.2, i'll have look

but what's the patch accept procedure, i create PR for 5.2 and it be later merged to master? or i create PR to master and it be latter merged to 5.2?

**Comment by oricgn** [comment]
Hi Elan,

I think we need a PR for both versions 5.2 and master.

You are using the mbstring extension which is a non-default extension. So we have to check also, if the the mbstring extension is available.

$PHORUM["DATA"]["HCHARSET"] should be set by the language file, but nevertheless it is possible to use mb_internal_encoding() in case HCHARSET is empty.

Your solution is not working for cut===TRUE. This option is used in Phorum when quoting messages. So the multi-byte safe wordwrap should handle both kinds of "cut".

If $str contains $break your function doesn't wrap correctly because a break doesn't reset $pl to 1.

I propose the following (more complex) function for a multi byte safe wordwrap:
https://github.com/oricgn/phorum-core/compare/phorum_5_2_strip_body...oricgn:phorum_5_2_phorum_wordwrap

Regards
Oliver

**Comment by glensc** [comment]
you need `global $PHORUM` in `_phorum_wordwrap`

**Comment by oricgn** [comment]
Hi Elan,

thanks for your hints. I committed an updated version.

Regards
Oliver

**Comment by glensc** [comment]
:+1: +1 for the PR & merge. if you took it from CakePHP, it means it's likely well tested.

**Comment by oricgn** [comment]
Done in phorum_5_2: https://github.com/Phorum/Core/commit/5efdb28bd592bb784afe32b9a12d393f198b5398

**Comment by glensc** [comment]
:+1:

**Comment by glensc** [comment]
btw, you said mbstring could be optional, but then you committed in mb_substr changes. is mb_substr overloaded to plain substr somewhere in phorum core that such change was okay?

**Comment by oricgn** [comment]
There is a mb_substr() implementation at the end of common.php.

**Comment by oricgn** [comment]
Done in master: https://github.com/Phorum/Core/commit/299412b03b12a68b701f97e071156d6c4a646192

**Comment by glensc** [comment]
btw, maybe some minor performance improvement. cache all those checks in static variable. that *may* give some improvement when method called several times on a page.

```php
function_exists('mb_internal_encoding')
         && function_exists('mb_strlen')
         && function_exists('mb_strpos')
         && function_exists('mb_strrpos')
         && function_exists('mb_substr') ) 
```

as such:
```php

static $has_mb;

if ($has_mb === null) {
         $has_mb = function_exists('mb_internal_encoding')
         && function_exists('mb_strlen')
         && function_exists('mb_strpos')
         && function_exists('mb_strrpos')
         && function_exists('mb_substr');
}


if ($has_mb) {
   // ...
} else {
   // ... 
}
```

**Comment by oricgn** [comment]
Done. Thanks for the advise.
